name: PR Build & Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v1
        # Spellcheck is only supported on pull requests for some reason.
        if: ${{ github.event_name == 'pull_request' }}
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - uses: mxschmitt/action-tmate@v3
      - run: dart analyze --fatal-infos
      - run: dart test
      - run: dart compile exe bin/hbot.dart